server:
  port: 8762

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # USER-SERVICE
        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        # ROLE-SERVICE
        - id: ROLE-SERVICE
          uri: lb://role-service
          predicates:
            - Path=/role-service/**

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY